on:
  push:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'build.zig'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: zig build --summary all
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: zig-out
          retention-days: 7
          if-no-files-found: error